def foo(first, second=3, third):
    print(first)
    print(second)
    print(third)

foo(42)

# will also error, only one default and only one argument passed in